### ISSUE TITLE
InterSystems Objectsript Contest

### ISSUE THREAD

**Issue by irinapodmazko** [jakcpto/promjet-stats#11]
Hi @jakcpto,
Here’s Iryna from the InterSystems team!
We noticed you participating in the InterSystems Objectsript Contest:
image

InterSystems prepared $$$ prizes for the winners. So we welcome you to our competition! Details here.

In order to win, you need to commit the ObjectScript repo to the github and show it to us (admins of InterSystems) + be registered on the InterSystems Developer Community.

Please let me know if you need any help with onboarding to our ObjectScript Contest and Community.

Happy coding!

Best regards,
Iryna from InterSystems Team

**Comment by jakcpto** [comment]
Ok, thanks
