### ISSUE TITLE
typo in short description

### ISSUE THREAD

**Issue by SergeyMi37** [jakcpto/promjet-stats#6]
![image](https://user-images.githubusercontent.com/18187317/132202430-2e1fc583-6278-4fc4-a3e6-adf55de6eee6.png)

**Comment by jakcpto** [comment]
I know, but I can`t correct this.
Editor is uneditable
https://github.com/intersystems-community/openexchange/issues/250

----
Потапов Евгений
тел: +79658410286



пн, 6 сент. 2021 г. в 14:21, Sergey Mikhaylenko ***@***.***>:
