### ISSUE TITLE
installation errors in docker

### ISSUE THREAD

**Issue by SergeyMi37** [jakcpto/promjet-stats#7]
....
IRISAPP>

ERROR! 'isc-dev' not found in any repository.
IRISAPP>

    DO ##CLASS(dev.code).workdir("/irisdev/app/src")
    ^
<CLASS DOES NOT EXIST> *dev.code
IRISAPP>

...
Load started on 09/06/2021 11:28:08
Loading file /opt/irisapp/module.xml as xml
Imported document: iris-PromJet.ZPM
Load finished successfully.

ERROR! Could not find satisfactory version of dsw in any repositories. Required by: iris-promjet: 3.*
IRISAPP>

IRISAPP>

%SYS>
1
%SYS>
Modifying MDX2JSON application security...

%SYS>

%SYS>

%SYS>

%SYS>

%SYS>

ERROR #869: Application /mdx2json does not exist1
%SYS>

%SYS>
Removing intermediate container 80213879e261
 ---> 16a93f9b9eed
Successfully built 16a93f9b9eed
Successfully tagged promjet-stats_iris:latest

**Comment by jakcpto** [comment]
@NjekTt look at this log, please.
